# Generated by Django 4.2.6 on 2023-12-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_gender_shit_kostyl_math_shit_delete_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='math_shit',
            name='user_id',
        ),
        migrations.AddField(
            model_name='kostyl',
            name='Ms',
            field=models.ManyToManyField(to='articles.math_shit'),
        ),
        migrations.AlterField(
            model_name='gender_shit',
            name='gender',
            field=models.CharField(choices=[(1, 'parquet'), (2, 'laminate'), (3, 'helicopter boss')], max_length=20, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='math_shit',
            name='math',
            field=models.CharField(choices=[(1, 'Gamma function'), (2, 'Series of inverse squares'), (3, 'Gaussian integral')], max_length=20, verbose_name='Fav_obj'),
        ),
    ]
