# Generated by Django 4.2.6 on 2023-12-25 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_yours_planet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kostyl',
            old_name='gender_id',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='yours_planet',
            old_name='user_id',
            new_name='user',
        ),
    ]
