# Generated by Django 4.2.6 on 2023-12-25 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0005_rename_gender_id_kostyl_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yours_planet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
