# Generated by Django 4.2.6 on 2023-12-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_yours_planet_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20, verbose_name='email')),
            ],
        ),
    ]
