# Generated by Django 4.2.6 on 2023-12-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_subb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ans1', models.IntegerField(default=0)),
                ('Ans2', models.IntegerField(default=0)),
                ('Ans3', models.IntegerField(default=0)),
            ],
        ),
    ]
