# Generated by Django 4.2.6 on 2024-01-05 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_opros'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Opros',
        ),
    ]
